pipeline{
    agent any
    stages{
        stage('checkout'){
            steps{
                script{
                    properties([pipelineTriggers([pollSCM('* * * * *')])])
                }
                git branch: 'main', url: 'https://github.com/cboldis/DevOps.git'
            }
        }
        stage('run backend server'){
            steps{
                bat 'start /min python pythonProject/rest_app.py'
            }
        }
        stage('run frontend server'){
            steps{
                bat 'start /min python pythonProject/web_app.py'
            }
        }
        stage('run backend testing'){
            steps{
                bat 'python pythonProject/backend_testing.py'
            }
        }
        stage('run frontend testing'){
            steps{
                bat 'python pythonProject/frontend_testing.py'
            }
        }
        stage('run combined testing'){
            steps{
                bat 'python pythonProject/combined_testing.py'
            }
        }
        stage('run clean environment'){
            steps{
                bat 'python pythonProject/clean_environment.py'
            }
        }
    }
}