pipeline{
    agent any
    stages{
        stage('checkout'){
            steps{
                script{
                    properties([pipelineTriggers([pollSCM('* * * * *')])])
                }
                git branch: 'main', url: 'https://github.com/cboldis/DevOps.git'
            }
        }
        stage('run backend server'){
            steps{
                bat 'start/min python pythonProject/rest_app.py'
            }
        }
        stage('run frontend server'){
            steps{
                bat 'start/min python pythonProject/web_app.py'
            }
        }

    }
}