pipeline{
    agent any
    stages{
        stage('Initialize Virtual Environment') {
            steps {
                script {
                    // Create and activate the virtual environment
                    bat 'python -m venv venv'
                    bat 'venv/Scripts/activate'

                    // Upgrade pip in the virtual environment
                    bat 'pip install --upgrade pip --user'
                }
            }
        }

        stage('Install pymysql') {
            steps {
                script {
                    // Install the pymysql package in the virtual environment
                    bat 'pip install pymysql'
                }
            }
        }
        stage('Install requests') {
            steps {
                script {
                    // Install the pymysql package in the virtual environment
                    bat 'pip install requests --user'
                }
            }
        }
        stage('Install flask') {
            steps {
                script {
                    // Install the pymysql package in the virtual environment
                    bat 'pip install flask --user'
                }
            }
        }
        stage('checkout'){
            steps{
                script{
                    properties([pipelineTriggers([pollSCM('* * * * *')])])
                }
                git branch: 'main', url: 'https://github.com/cboldis/DevOps.git'
            }
        }
        stage('run backend server'){
            steps{
                bat 'python pythonProject/rest_app.py'
            }
        }
        stage('run frontend server'){
            steps{
                bat 'python pythonProject/web_app.py'
            }
        }
        stage('run backend testing'){
            steps{
                bat 'python pythonProject/backend_testing.py'
            }
        }
        stage('run frontend testing'){
            steps{
                bat 'python pythonProject/frontend_testing.py'
            }
        }
        stage('run combined testing'){
            steps{
                bat 'python pythonProject/combined_testing.py'
            }
        }
        stage('run clean environment'){
            steps{
                bat 'python pythonProject/clean_environment.py'
            }
        }
    }
}